# Generated by Django 2.1.7 on 2020-06-22 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200620_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.devices'),
        ),
    ]
