# Generated by Django 3.0.7 on 2020-08-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tickets_email_as_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='email_as_send',
            field=models.BooleanField(default=False),
        ),
    ]
